name: testi

on:
  push:
    branches:
      - master

jobs:
  preveri_teste:
    runs-on: ubuntu-latest
    outputs:
      testi: ${{ steps.check_files.outputs.testi }}
    steps:
      - uses: actions/checkout@v3
      - name: Preverba testov
        id: check_files
        run: |
          if compgen -G "tests/test_*.py" > /dev/null; then
            echo "::set-output name=testi::true"
          else
            echo "::set-output name=testi::false"
          fi

  run_tests:
    needs: preveri_teste
    if: ${{ needs.preveri_teste.outputs.testi == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Nastavim Python environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: namestitev odvisnosti
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest tests/
        continue-on-error: true
      - name: Capture errors
        if: ${{ failure() }}
        run: echo "Tests niso uspelu" > error.txt
        continue-on-error: true
      - name: naložim artefakt če so testi neuspesni
        uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: error-report
          path: error.txt
