name: deploy

on:
  workflow_run:
    workflows: ["testi"]
    branches: [master]
    types:
      - completed

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: zgradim Docker image
        run: |
          docker build -t zanlah/filtriapp:${{ github.sha }} .
      - name: Prijava DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push Docker image
        run: |
          docker push zanlah/filtriapp:${{ github.sha }}
