name: deploy

on:
  workflow_run:
    workflows: ["testi"]
    branches: [master]
    types:
      - completed

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: nastavi pravice
        run: chmod +x zapakiraj_27117.sh
      - name: deploy
        run: ./zapakiraj_27117.sh
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          GITHUB_SHA: ${{ github.sha }}
