name: testi

on:
  push:
    branches:
      - master

jobs:
  preveri_teste:
    runs-on: ubuntu-latest
    outputs:
      testi_obstajajo: ${{ steps.preveri_datoteke.outputs.testi_obstajajo }}
    steps:
      - uses: actions/checkout@v3
      - name: Preverba testov
        id: preveri_datoteke
        run: |
          if ! compgen -G "tests/test_*.py" > /dev/null; then
            echo "Testi niso najdeni" > napaka.txt
          fi
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: error-report
          path: napaka.txt

  run_tests:
    needs: preveri_teste
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v3
      - name: Nalozi datoteko s napakami
        uses: actions/download-artifact@v2
        with:
          name: error-report
      - name: Preveri datoteko s napakami
        run: |
          if [ -s napaka.txt ]; then
            cat napaka.txt
            exit 1
          fi
      - name: Nastavim Python okolje
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Nalozin odvisnosti
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Zazeni teste
        run: pytest tests/
        continue-on-error: true
      - name: Ulovi napake ce so testi neuspesni
        if: ${{ failure() }}
        run: echo "Tests niso uspeli" > napaka.txt
      - uses: actions/upload-artifact@v2
        if: ${{ failure() }}
        with:
          name: error-report
          path: napaka.txt
